#!/bin/sh

# navigate to a git directory under the current directory
jj() {
    cd "${1:-.}/$(find . -maxdepth 5 -type d -name .git | sed 's|/.git$||' | fzf --preview 'tree -L 2 ./{}')" || return 1
}

# use view to see a list of temporary git workspaces
# otherwise create a new temporary workspace
tmp() {
  [ "$1" = "view" ] && cd /tmp/workspaces &&
    cd $(ls -t | fzf --preview 'ls -A {}') &&
    return 0
  r="/tmp/workspaces/$(xxd -l3 -ps /dev/urandom)"
  mkdir -p "$r" && pushd "$r"
  git init
}

# Go to root of project
r() {
  pushd "$(git rev-parse --show-toplevel 2>/dev/null)" || return 1
}

# make a directory and change into it
take() {
  mkdir -p "$1" && cd "$1" || return 1
}

# make clear not delete scrollback
# https://superuser.com/a/1667623/328228
clear() (
    if [ "$#" -ne 0 ]; then
        command clear "$@"
        exit
    fi
    h="$(tput lines 2>/dev/null)"
    if [ "$?" -eq 0 ]; then
        until [ "$h" -le 1 ]; do
            printf '\n'
            h=$((h - 1))
        done
    fi
    command clear -x
)

# Create a tmp dir, unzip file into it, cd into it
,showme() {
  [ -z "$1" ] && echo "Pass file to show" && return 1
  [ ! -r "$1" ] && echo "Cannot read file" && return 1

  tmp="$(mktemp -d)"

  case "$1" in
    *.zip)
      unzip "$1" -d "$tmp"
      ;;
    *.tar.* | *.tgz | *.tar)
      tar -xf "$1" -C "$tmp"
      ;;
    *)
      echo "Unsupport file extension"
      return 1
      ;;
  esac

  cd "$tmp" || return 1
  clear && echo && echo "$1" && ls
}
